// SPDX-License-Identifier: AGPL-3.0-only
//
// THE COMMAND CATALOGUE (API-1, CS-15.18), generated by `scripts/command-parity.mjs`,
// and the parity check holding every surface to the owning command. It replaces
// capability-map discovery, not ported (issue 55). It reads no record.

import {
  COMMAND_SURFACE,
  PREFIX,
  pathOf,
  type CommandDeclaration,
  type CommandName,
} from './surface.ts';

/** A place in the app that calls a command; `file` is relative to apps/web/src. */
export type UiUse = { readonly command: string; readonly route: string; readonly file: string };

/** What a surface asks before it runs a command. The same on every surface, or parity fails. */
export interface Profile {
  // every key checked inside, two for a two-part authority
  readonly authority: readonly string[];
  // wider reads what narrower refuses
  readonly authorisedOn: CommandDeclaration['authorisedOn'];
  // refuses every agent credential, delegation or not, everywhere
  readonly personOnly: boolean;
  // a hold every path keeps before it writes
  readonly rule: string;
}

export interface CatalogueRow extends Profile {
  readonly command: CommandName;
  readonly kind: 'read' | 'write';
  // never, delegated, or also before a pickup
  readonly agent: CommandDeclaration['agent'];
  readonly permissionKey: string;
  readonly api: { readonly person: string; readonly agent: string | null };
  readonly cli: string;
  // `route (file)` per place the app calls it; empty: none yet
  readonly ui: readonly string[];
  // S0-5 (U18) fills it: whether it admits a new outside person
  readonly dataEffects: null;
}

/** A UI action with no command, and why it needs none (CS-15.18). */
export type Exempt = { readonly action: string; readonly reason: string };

export const VIEW_ONLY_EXEMPT: readonly Exempt[] = [
  { action: 'navigate', reason: 'changes the address; the page reads through its own command' },
  { action: 'focus', reason: 'moves keyboard focus; nothing is read or written' },
  { action: 'scroll', reason: 'moves the view; nothing is read or written' },
  { action: 'open or close a dock', reason: 'view state; its contents read through a command' },
  { action: 'switch a tab', reason: 'view state; the tab reads through its own command' },
];

/** Keys an agent never holds (contract 2.3 to 2.6). */
const PERSON_ACTIONS: ReadonlySet<string> = new Set(['decide', 'share', 'manage']);

const actionOf = (key: string): string => key.slice(key.indexOf(':') + 1);

/** The profile the owning command declares, which every surface must ask. */
export function profileOf(declaration: CommandDeclaration): Profile {
  const key = `${declaration.collection}:${declaration.action}`;
  // A self-scoped row asks no grant: every signed-in person reaches their own rows.
  const authority = declaration.authorisedOn === 'self' ? [] : (declaration.authority ?? [key]);
  return {
    authority,
    authorisedOn: declaration.authorisedOn,
    personOnly:
      declaration.agent === 'never' || authority.some((one) => PERSON_ACTIONS.has(actionOf(one))),
    rule: declaration.rule ?? '',
  };
}

export function buildCatalogue(
  uses: readonly UiUse[],
  declarations: readonly CommandDeclaration[] = COMMAND_SURFACE,
): CatalogueRow[] {
  return declarations.map((declaration) => {
    const profile = profileOf(declaration);
    const path = pathOf(declaration.name);
    const ui = uses
      .filter((use) => use.command === declaration.name)
      .map((use) => `${use.route} (${use.file})`);
    return {
      command: declaration.name,
      kind: declaration.kind,
      agent: declaration.agent,
      permissionKey: `${declaration.collection}:${declaration.action}`,
      ...profile,
      api: {
        person: `${PREFIX.person}:businessKey${path}`,
        agent: profile.personOnly ? null : `${PREFIX.agent}:businessKey${path}`,
      },
      cli: declaration.name,
      ui: [...new Set(ui)].toSorted(),
      dataEffects: null,
    };
  });
}

type Reach = ReadonlyMap<string, Profile>;
export type Surfaces = Readonly<Record<'api' | 'agent' | 'cli' | 'web', Reach>> & {
  readonly ui: readonly UiUse[];
  readonly exempt: readonly Exempt[];
};

function compare(surface: string, command: string, owned: Profile, asked: Profile): string[] {
  const at = `${surface} ${command}`;
  const scope = `${at} asks at ${asked.authorisedOn} scope where the app asks at ${owned.authorisedOn}`;
  return [
    ...owned.authority.flatMap((key) =>
      asked.authority.includes(key) ? [] : [`${at} skips the grant check ${key} the app makes`],
    ),
    ...(asked.authorisedOn === owned.authorisedOn ? [] : [scope]),
    ...(owned.personOnly && !asked.personOnly
      ? [`${at} drops the person-only marker and admits an agent`]
      : []),
    ...(asked.rule === owned.rule
      ? []
      : [`${at} passes the hold the app keeps: ${owned.rule || 'none'}`]),
  ];
}

/** Every way the catalogue and surfaces disagree, as plain lines; empty is parity. */
export function checkParity(
  rows: readonly CatalogueRow[],
  surfaces: Surfaces,
  declarations: readonly CommandDeclaration[] = COMMAND_SURFACE,
): string[] {
  const failures: string[] = [];
  const owned = new Map(declarations.map((one) => [one.name as string, profileOf(one)]));
  const { api, agent, cli, web } = surfaces;
  const reaches = Object.entries({ API: api, 'agent API': agent, CLI: cli, app: web });
  for (const [name, profile] of owned) {
    const row = rows.find((one) => one.command === name);
    if (row === undefined) failures.push(`the catalogue has no row for ${name}`);
    else failures.push(...compare('catalogue row', name, profile, row));
    for (const [surface, reach] of reaches) {
      const asked = reach.get(name);
      if (asked === undefined) failures.push(`${name} has no ${surface} equivalent`);
      else failures.push(...compare(surface, name, profile, asked));
    }
  }
  for (const [surface, reach] of reaches) {
    for (const name of reach.keys()) {
      if (!owned.has(name)) failures.push(`${surface} reaches ${name}, which no command owns`);
    }
  }
  for (const row of rows) {
    if (!owned.has(row.command)) failures.push(`the catalogue row ${row.command} has no command`);
    const heldByAgent = row.authority.filter((key) => PERSON_ACTIONS.has(actionOf(key)));
    if (!row.personOnly && heldByAgent.length > 0) {
      failures.push(`${row.command} is agent-eligible and holds ${heldByAgent.join(', ')}`);
    }
  }
  for (const use of surfaces.ui) {
    const at = `the app action ${use.command} at ${use.route} (${use.file})`;
    if (!surfaces.cli.has(use.command)) failures.push(`${at} has no CLI verb`);
    if (!surfaces.api.has(use.command)) failures.push(`${at} has no API endpoint`);
  }
  for (const { action } of surfaces.exempt) {
    if (owned.has(action)) failures.push(`${action} reads or writes a record and cannot be exempt`);
  }
  return failures;
}

export interface HeldGrant {
  readonly key: string;
  readonly scope: { readonly kind: 'business' | 'party' | 'record'; readonly id: string | null };
}

// Which commands `principal` may call, and where (issue 55). Business-scoped needs business-wide
// keys; an agent reaches queue and pickup holding nothing (8.2) and never the person-only app.
// A row asking no grant: a self-scoped write reaches anyone's own rows; a read (the inbox,
// session.capabilities) is served only to a holder of some live grant, as its handler refuses.
export function reachableBy(
  rows: readonly CatalogueRow[],
  principal: { readonly kind: 'person' | 'agent'; readonly grants: readonly HeldGrant[] },
): { readonly command: CommandName; readonly surfaces: readonly string[] }[] {
  const agent = principal.kind === 'agent';
  const holds = (key: string, wide: boolean) =>
    principal.grants.some((one) => one.key === key && (!wide || one.scope.kind === 'business'));
  return rows
    .filter((row) => !agent || !row.personOnly)
    .filter(
      (row) =>
        (agent && row.agent === 'before-pickup') ||
        (row.authority.length === 0
          ? (row.kind === 'write' && row.authorisedOn === 'self') || principal.grants.length > 0
          : row.authority.every((key) => holds(key, row.authorisedOn === 'business'))),
    )
    .map((row) => ({
      command: row.command,
      surfaces: [...(!agent && row.ui.length > 0 ? ['app'] : []), 'API', 'CLI'],
    }));
}

/** The owner's parity report: every button that changes something, with its CLI command. */
export function renderReport(rows: readonly CatalogueRow[], failures: readonly string[]): string {
  const buttons = rows.filter((row) => row.kind === 'write' && row.ui.length > 0);
  const lines = [
    '# Command parity report\n',
    '| App action | Where | CLI command | API endpoint | Key |',
    '| --- | --- | --- | --- | --- |',
    ...buttons.map(
      (row) =>
        `| ${row.command} | ${row.ui.join('; ')} | \`pnpm cli ${row.cli}\` | ${row.api.person} | ${row.permissionKey} |`,
    ),
    failures.length === 0
      ? `\n${String(buttons.length)} app actions change something; each has its CLI command. None is missing.`
      : `\nMissing or unequal:\n${failures.map((line) => `- ${line}`).join('\n')}`,
    '\nExempt, view only:',
    ...VIEW_ONLY_EXEMPT.map((one) => `- ${one.action}: ${one.reason}`),
  ];
  return `${lines.join('\n')}\n`;
}
