-- SPDX-License-Identifier: AGPL-3.0-only
--
-- 0047 the API's outbox (ticket S0-2; the Vercel re-plan, section 11 step 2;
-- the orchestrator's ruling STEP2-SHAPE).
--
-- On Vercel each function instance has its own memory and no route to the
-- error sink on the machine, so an API instance keeps no count and sends
-- nothing: it appends each security signal and each error here, and the
-- environment's worker forwards, counts, raises and deletes
-- (`apps/worker`, as `ops_astro_forwarder`).
--
-- A signal or an error often comes before any business is known, so the table
-- belongs to none. The application group may insert its four columns and
-- nothing else: it reads, changes and removes no row, and the time is the
-- database's own. A scope is a keyed digest the API computes (HMAC under a
-- deploy-time key), never a business key, subject, address or source; an
-- error is its bounded event (`apps/api/alerts/sink.ts`, `errorEvent`).

create table ops.api_events (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('error', 'sign-in-failed', 'authority-changed',
    'secret-scan-failed', 'cross-scope-refusal', 'webhook-signature-failed', 'export')),
  scope text not null default '' check (scope ~ '^([0-9a-f]{64})?$'),
  weight integer not null default 1 check (weight > 0),
  event jsonb check ((kind = 'error') = (event is not null)),
  at timestamptz not null default now()
);
revoke all on ops.api_events from public;
grant insert (kind, scope, weight, event) on ops.api_events to ops_astro_app;

-- The forwarder: made with every attribute said out loud, and altered only
-- when a role made earlier differs (as 0045 and 0046 do).
do $$ begin
  create role ops_astro_forwarder nologin nosuperuser nocreatedb nocreaterole noreplication nobypassrls;
exception when duplicate_object or unique_violation then null;
end $$;

do $$ begin
  if exists (select 1 from pg_roles where rolname = 'ops_astro_forwarder' and (rolcanlogin
      or rolsuper or rolcreatedb or rolcreaterole or rolreplication or rolbypassrls)) then
    alter role ops_astro_forwarder nologin nosuperuser nocreatedb nocreaterole noreplication nobypassrls;
  end if;
end $$;

grant usage on schema ops to ops_astro_forwarder;
grant select, delete on ops.api_events to ops_astro_forwarder;

comment on role ops_astro_forwarder is
  'Outbox forwarder. Reads and deletes ops.api_events; nothing else, no login of its own.';
