-- SPDX-License-Identifier: AGPL-3.0-only
--
-- 0048 the forwarder's raised alerts, waiting to be sent (ticket S0-2; Sol's
-- REVB1SL01S2C). An alert the forwarder raises from the outbox (0047) is
-- written here with its sink id, and the signals it counted are deleted, in
-- one committed step; it is sent from here and deleted only once the sink
-- took it. A send whose answer is lost leaves it here, so the retry sends the
-- same id whatever signals commit later. It holds an alert's kind and id
-- alone: no scope, business or person. The application group holds nothing
-- on it.

create table ops.api_alerts (
  seq bigint generated by default as identity,
  id text primary key check (id ~ '^[0-9a-f]{32}$'),
  kind text not null check (kind ~ '^[a-z-]{1,40}$'),
  at timestamptz not null default now()
);
revoke all on ops.api_alerts from public;
grant select, insert, delete on ops.api_alerts to ops_astro_forwarder;
