-- SPDX-License-Identifier: AGPL-3.0-only
--
-- 0067 the security alert log (C55, TR-SEC-9; the orchestrator's ruling
-- ORCH47 (b)6). The forwarder deletes an alert from `ops.api_alerts` (0048)
-- once the sink took it, so the operations view cannot list alerts from
-- there. Each alert the forwarder raises is also written here, in the same
-- statement and transaction that keeps it in `ops.api_alerts` (an alert
-- already kept is not written twice), and nothing here is deleted by a send.
--
-- A row is an alert's kind and the time it was raised, and nothing else: no
-- sink id, scope, business, client, person, secret or record content. The
-- time is the database's own. The forwarder may insert the kind alone. The
-- application group may select the kind and the time alone, and reads them
-- only for the business that operates the installation
-- (`ops.installation.operator_business_id`, 0062), newest first, at most 50
-- (`core-records/src/operations/security-alerts.ts`). It inserts, changes and
-- removes nothing, and still holds nothing on `ops.api_alerts`. PUBLIC holds
-- nothing.

create table ops.security_alert_log (
  seq bigint generated by default as identity primary key,
  kind text not null check (kind ~ '^[a-z-]{1,40}$'),
  at timestamptz not null default now()
);
create index security_alert_log_newest on ops.security_alert_log (at desc);
revoke all on ops.security_alert_log from public;
grant insert (kind) on ops.security_alert_log to ops_astro_forwarder;
grant select (kind, at) on ops.security_alert_log to ops_astro_app;
