-- SPDX-License-Identifier: AGPL-3.0-only
--
-- 0222 team invitations, their enrolment tokens and their delivery attempts (C39-T).
--
-- An invitation names the enduring person it was made for (a `people` row
-- written with it), the role they are invited to, the address the link goes
-- to, and its state: pending until accepted, revoked or expired. Its acts
-- (create, resend, revoke) are commands, each audited by the envelope; expiry
-- is the business's worker's. `revision` counts the moves.
--
-- An enrolment token is minted by the send, one per act, and kept as its
-- SHA-256 alone: the token itself exists only in the link the email carries.
-- Nothing is ever kept from which the token could be rebuilt.
--
-- A delivery attempt is one observation of one send, keyed by the token the
-- send minted, as `inbox_delivery_attempts` is keyed by its item: asked, then
-- accepted or failed. Observations are never rewritten.
--
-- Rate limits are counted from these rows and the audit chain, under the
-- durable limiter's locks: there is no counter table.

create table public.invitations (
  business_id         uuid        not null,
  id                  uuid        not null,
  person_id           uuid        not null,
  role_key            text        not null,
  -- The normalised address: trimmed and lower case.
  address             text        not null,
  state               text        not null default 'pending',
  expires_at          timestamptz not null,
  created_by_actor_id uuid        not null,
  created_at          timestamptz not null default now(),
  ended_at            timestamptz,
  revision            integer     not null default 1,
  constraint invitations_pkey primary key (id),
  constraint invitations_tenant_id_key unique (business_id, id),
  constraint invitations_business_fkey foreign key (business_id, business_id)
    references public.businesses (business_id, id),
  constraint invitations_person_fkey foreign key (business_id, person_id)
    references public.people (business_id, id),
  constraint invitations_creator_fkey foreign key (business_id, created_by_actor_id)
    references public.actors (business_id, id),
  constraint invitations_role_key_shape check (role_key ~ '^[a-z][a-z0-9_]*$'),
  constraint invitations_address_shape
    check (address = lower(btrim(address)) and address ~ '^[^@[:space:]]+@[^@[:space:]]+$'),
  constraint invitations_state_known
    check (state in ('pending', 'accepted', 'revoked', 'expired')),
  constraint invitations_ended_when_not_pending check ((state = 'pending') = (ended_at is null)),
  constraint invitations_revision_positive check (revision >= 1)
);

-- One pending invitation per address in a business.
create unique index invitations_one_pending_address
  on public.invitations (business_id, address) where state = 'pending';

create index invitations_creator_idx
  on public.invitations (business_id, created_by_actor_id, created_at);

create table public.enrolment_tokens (
  business_id   uuid        not null,
  id            uuid        not null,
  invitation_id uuid        not null,
  -- SHA-256 of the token, lower-case hex. Never the token.
  token_hash    text        not null,
  created_at    timestamptz not null default now(),
  expires_at    timestamptz not null,
  spent_at      timestamptz,
  constraint enrolment_tokens_pkey primary key (id),
  constraint enrolment_tokens_tenant_id_key unique (business_id, id),
  constraint enrolment_tokens_invitation_id_key unique (business_id, invitation_id, id),
  constraint enrolment_tokens_hash_key unique (business_id, token_hash),
  constraint enrolment_tokens_business_fkey foreign key (business_id, business_id)
    references public.businesses (business_id, id),
  constraint enrolment_tokens_invitation_fkey foreign key (business_id, invitation_id)
    references public.invitations (business_id, id),
  constraint enrolment_tokens_hash_shape check (token_hash ~ '^[0-9a-f]{64}$')
);

create table public.invitation_delivery_attempts (
  business_id   uuid        not null,
  id            uuid        not null,
  invitation_id uuid        not null,
  token_id      uuid        not null,
  state         text        not null,
  evidence      text,
  observed_at   timestamptz not null default now(),
  -- Causal order: observations in one transaction share `now()`, not this.
  observed_seq  bigint      generated by default as identity,
  constraint invitation_delivery_attempts_pkey primary key (id),
  constraint invitation_delivery_attempts_tenant_id_key unique (business_id, id),
  constraint invitation_delivery_attempts_business_fkey foreign key (business_id, business_id)
    references public.businesses (business_id, id),
  constraint invitation_delivery_attempts_token_fkey
    foreign key (business_id, invitation_id, token_id)
    references public.enrolment_tokens (business_id, invitation_id, id),
  constraint invitation_delivery_attempts_state_known
    check (state in ('asked', 'accepted', 'delivered', 'failed'))
);

create index invitation_delivery_attempts_invitation_idx
  on public.invitation_delivery_attempts (business_id, invitation_id);

alter table public.invitations enable row level security;
alter table public.invitations force row level security;
alter table public.enrolment_tokens enable row level security;
alter table public.enrolment_tokens force row level security;
alter table public.invitation_delivery_attempts enable row level security;
alter table public.invitation_delivery_attempts force row level security;

create policy tenancy_invitations on public.invitations
  as restrictive for all
  using (business_id = (select public.app_business_id()))
  with check (business_id = (select public.app_business_id()));

create policy authority_invitations on public.invitations
  as permissive for all using (true) with check (true);

create policy tenancy_enrolment_tokens on public.enrolment_tokens
  as restrictive for all
  using (business_id = (select public.app_business_id()))
  with check (business_id = (select public.app_business_id()));

create policy authority_enrolment_tokens on public.enrolment_tokens
  as permissive for all using (true) with check (true);

create policy tenancy_invitation_delivery_attempts on public.invitation_delivery_attempts
  as restrictive for all
  using (business_id = (select public.app_business_id()))
  with check (business_id = (select public.app_business_id()));

create policy authority_invitation_delivery_attempts on public.invitation_delivery_attempts
  as permissive for all using (true) with check (true);

-- The invitation moves by these four columns alone (state, ended_at,
-- expires_at, revision): who it is for, its role, its address and who made it
-- are fixed at create. An attempt's observations are written once and never
-- rewritten. A token moves once, by `spent_at` alone, when the invitation is
-- accepted (P3).
grant select, insert on public.invitations to ops_astro_app;
grant update (state, ended_at, expires_at, revision) on public.invitations to ops_astro_app;
grant select, insert on public.enrolment_tokens to ops_astro_app;
grant update (spent_at) on public.enrolment_tokens to ops_astro_app;
grant select, insert on public.invitation_delivery_attempts to ops_astro_app;
